From openjdk
WorkDIR /usr/src
ENV MYSQL_HOST=localhost
ENV MYSQL_DATABASE=user_records
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=root

COPY ./target/User-0.0.1-SNAPSHOT.jar User-0.0.1-SNAPSHOT.jar
#EXPOSE 8006
ENTRYPOINT ["java","-jar","/usr/src/User-0.0.1-SNAPSHOT.jar"]
